// wireshark lua dissector generator
// produces a .lua plugin that can be dropped into the wireshark plugins dir

use std::io::{self, Write};
use crate::ffi::{ProtocolSchema, FieldTypeId};

pub fn emit<W: Write>(out: &mut W, schema: &ProtocolSchema, proto_name: &str) -> io::Result<()> {
    let pname = proto_name.to_ascii_lowercase().replace(' ', "_");

    writeln!(out, "-- auto-generated by ref2, do not edit")?;
    writeln!(out, "-- load: copy to ~/.config/wireshark/plugins/ or %%APPDATA%%/Wireshark/plugins/")?;
    writeln!(out)?;
    writeln!(out, "local proto_{name} = Proto(\"{name}\", \"{name} protocol\")",
             name = pname)?;
    writeln!(out)?;

    // declare fields
    writeln!(out, "-- field declarations")?;
    for ms in &schema.schemas {
        for f in &ms.fields {
            let ws_type = field_ws_type(f.field_type, f.length);
            writeln!(out,
                "local f_{schema}_{fname} = ProtoField.{ws_type}(\"{pname}.{schema}.{fname}\", \"{fname}\")",
                schema = ms.name,
                fname  = f.name,
                pname  = pname,
                ws_type = ws_type,
            )?;
        }
    }
    writeln!(out)?;

    // register fields
    writeln!(out, "proto_{name}.fields = {{", name = pname)?;
    for ms in &schema.schemas {
        for f in &ms.fields {
            writeln!(out, "    f_{schema}_{fname},",
                     schema = ms.name, fname = f.name)?;
        }
    }
    writeln!(out, "}}")?;
    writeln!(out)?;

    // dissect function
    writeln!(out, "function proto_{name}.dissector(buf, pinfo, tree)", name = pname)?;
    writeln!(out, "    pinfo.cols.protocol = \"{name}\"", name = pname.to_uppercase())?;
    writeln!(out, "    local subtree = tree:add(proto_{name}, buf(), \"{name}\")",
             name = pname)?;
    writeln!(out)?;
    writeln!(out, "    -- ref2 infers message type from a discriminator field.")?;
    writeln!(out, "    -- adjust the offset/length below to match your capture.")?;
    writeln!(out)?;

    // emit a simple sequential decoder for the first message type as example
    // real usage would switch on the type discriminator
    if let Some(ms) = schema.schemas.first() {
        writeln!(out, "    -- example: decode as {} (type 0)", ms.name)?;
        writeln!(out, "    local offset = 0")?;
        for f in &ms.fields {
            let nbytes = if f.length == 0 {
                // variable — consume the rest
                writeln!(out, "    -- {fname}: variable-length payload",
                         fname = f.name)?;
                writeln!(out,
                    "    subtree:add(f_{schema}_{fname}, buf(offset, buf:len() - offset))",
                    schema = ms.name, fname = f.name)?;
                writeln!(out, "    offset = buf:len()")?;
                continue;
            } else {
                f.length
            };
            writeln!(out,
                "    subtree:add(f_{schema}_{fname}, buf(offset, {n}))",
                schema = ms.name, fname = f.name, n = nbytes)?;
            writeln!(out, "    offset = offset + {}", nbytes)?;
        }
        writeln!(out, "    _ = offset  -- suppress unused warning")?;
    }

    writeln!(out, "end")?;
    writeln!(out)?;

    // register on a port — leave it commented, user fills in
    writeln!(out, "-- uncomment and set the correct port:")?;
    writeln!(out, "-- local tcp_port = DissectorTable.get(\"tcp.port\")")?;
    writeln!(out, "-- tcp_port:add(1234, proto_{name})", name = pname)?;
    writeln!(out)?;
    writeln!(out, "-- or register as heuristic dissector:")?;
    writeln!(out, "-- proto_{name}:register_heuristic(\"tcp\", function(buf, pinfo, tree)",
             name = pname)?;
    writeln!(out, "--     if buf:len() < 4 then return false end")?;
    writeln!(out, "--     proto_{name}.dissector(buf, pinfo, tree)", name = pname)?;
    writeln!(out, "--     return true")?;
    writeln!(out, "-- end)")?;

    Ok(())
}

fn field_ws_type(ft: FieldTypeId, len: usize) -> &'static str {
    use FieldTypeId::*;
    match ft {
        Magic | Constant => match len {
            1 => "uint8",
            2 => "uint16",
            4 => "uint32",
            _ => "bytes",
        },
        Length | SequenceNumber => match len {
            1 => "uint8",
            2 => "uint16",
            4 => "uint32",
            _ => "uint32",
        },
        Enum => match len {
            1 => "uint8",
            2 => "uint16",
            _ => "uint32",
        },
        Nonce         => "bytes",
        Str           => "stringz",
        Payload       => "bytes",
        Opaque        => "bytes",
    }
}
