/// Scapy dissector generator.

use std::io::{self, Write};
use crate::ffi::{ProtocolSchema, FieldTypeId};

pub fn emit<W: Write>(out: &mut W, schema: &ProtocolSchema) -> io::Result<()> {
    writeln!(out, "# auto-generated by ref2 — do not edit manually")?;
    writeln!(out, "from scapy.packet import Packet")?;
    writeln!(out, "from scapy.fields import *")?;
    writeln!(out)?;

    for ms in &schema.schemas {
        let class_name = to_camel_case(&ms.name);
        writeln!(out, "class {}(Packet):", class_name)?;
        writeln!(out, "    name = {:?}", ms.name)?;
        writeln!(out, "    fields_desc = [")?;

        for (fi, f) in ms.fields.iter().enumerate() {
            let scapy_field = field_to_scapy(f, &ms.fields, fi);
            writeln!(out, "        {},", scapy_field)?;
        }

        writeln!(out, "    ]")?;
        writeln!(out)?;
    }

    Ok(())
}

fn to_camel_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None    => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}

fn field_to_scapy(f: &crate::ffi::Field, all_fields: &[crate::ffi::Field], idx: usize) -> String {
    use FieldTypeId::*;
    let name = &f.name;

    match f.field_type {
        Magic | Constant => {
            match f.length {
                1 => format!("ByteField({:?}, 0x{:02x})", name,
                              f.example_byte.unwrap_or(0)),
                2 => format!("XShortField({:?}, 0)", name),
                4 => format!("XIntField({:?}, 0)", name),
                n => format!("StrFixedLenField({:?}, b'', length={})", name, n),
            }
        }
        Enum => {
            let vals: String = f.enum_values[..f.enum_count]
                .iter()
                .enumerate()
                .map(|(i, &v)| format!("{}: \"val_{:02}\"", v, i))
                .collect::<Vec<_>>()
                .join(", ");
            match f.length {
                1 => format!("ByteEnumField({:?}, 0, {{{}}})", name, vals),
                2 => format!("ShortEnumField({:?}, 0, {{{}}})", name, vals),
                _ => format!("IntEnumField({:?}, 0, {{{}}})", name, vals),
            }
        }
        Length => {
            match f.length {
                1 => format!("ByteField({:?}, 0)", name),
                2 => format!("ShortField({:?}, 0)", name),
                4 => format!("IntField({:?}, 0)", name),
                _ => format!("StrFixedLenField({:?}, b'', length={})", name, f.length),
            }
        }
        SequenceNumber => {
            match f.length {
                1 => format!("ByteField({:?}, 0)", name),
                2 => format!("ShortField({:?}, 0)", name),
                4 => format!("IntField({:?}, 0)", name),
                _ => format!("StrFixedLenField({:?}, b'', length={})", name, f.length),
            }
        }
        Payload => {
            // Try to find a length field to reference.
            let len_field = all_fields.iter().find(|x| x.field_type == Length);
            if let Some(lf) = len_field {
                let hdr_bytes: usize = all_fields[..idx].iter()
                    .filter(|x| x.length > 0)
                    .map(|x| x.length)
                    .sum();
                format!("StrLenField({:?}, b\"\", length_from=lambda p: p.{} - {})",
                        name, lf.name, hdr_bytes)
            } else {
                format!("StrField({:?}, b\"\")", name)
            }
        }
        Nonce => {
            match f.length {
                0 => format!("StrField({:?}, b\"\")", name),
                n => format!("StrFixedLenField({:?}, b'', length={})", name, n),
            }
        }
        Str => format!("StrNullField({:?}, b\"\")", name),
        _ => {
            if f.length == 0 {
                format!("StrField({:?}, b\"\")", name)
            } else {
                format!("StrFixedLenField({:?}, b'', length={})", name, f.length)
            }
        }
    }
}
